#!/usr/bin/env python

from itemdef_itemtype import ItemType

suffix1 = []
suffix1.insert(ItemType.MELEE_HEAD, "")
suffix1.insert(ItemType.RANGED_HEAD, "")
suffix1.insert(ItemType.MENT_HEAD, "")
suffix1.insert(ItemType.MELEE_CHEST, "Cloth Shirt")
suffix1.insert(ItemType.RANGED_CHEST, "Cloth Shirt")
suffix1.insert(ItemType.MENT_CHEST, "Cloth Shirt")
suffix1.insert(ItemType.MELEE_LEGS, "Cloth Pants")
suffix1.insert(ItemType.RANGED_LEGS, "Cloth Pants")
suffix1.insert(ItemType.MENT_LEGS, "Cloth Pants")
suffix1.insert(ItemType.MELEE_FEET, "Cloth Sandals")
suffix1.insert(ItemType.RANGED_FEET, "Cloth Sandals")
suffix1.insert(ItemType.MENT_FEET, "Cloth Sandals")
suffix1.insert(ItemType.MELEE_HANDS, "Cloth Gloves")
suffix1.insert(ItemType.RANGED_HANDS, "Cloth Gloves")
suffix1.insert(ItemType.MENT_HANDS, "Cloth Gloves")
suffix1.insert(ItemType.MELEE_ARTIFACT, "Leather Belt")
suffix1.insert(ItemType.RANGED_ARTIFACT, "Pendant")
suffix1.insert(ItemType.MENT_ARTIFACT, "Spellbook")
suffix1.insert(ItemType.MELEE_WEAPON, "Dagger")
suffix1.insert(ItemType.RANGED_WEAPON, "Slingshot")
suffix1.insert(ItemType.MENT_WEAPON, "Wand")
suffix1.insert(ItemType.SHIELD, "Wood Buckler")
suffix1.insert(ItemType.FIRE_RING, "Fire Ring")
suffix1.insert(ItemType.ICE_RING, "Ice Ring")
suffix1.insert(ItemType.SHOCK_RING, "Lightning Ring")
suffix1.insert(ItemType.DARK_RING, "Dark Ring")
suffix1.insert(ItemType.XP_RING, "Experience Ring")
suffix1.insert(ItemType.GOLD_RING, "Wealth Ring")
suffix1.insert(ItemType.ITEM_RING, "Treasure Ring")

suffix2 = []
suffix2.insert(ItemType.MELEE_HEAD, "Leather Hood")
suffix2.insert(ItemType.RANGED_HEAD, "Leather Hood")
suffix2.insert(ItemType.MENT_HEAD, "Wool Hood")
suffix2.insert(ItemType.MELEE_CHEST, "Leather Tunic")
suffix2.insert(ItemType.RANGED_CHEST, "Leather Tunic")
suffix2.insert(ItemType.MENT_CHEST, "Wool Vest")
suffix2.insert(ItemType.MELEE_LEGS, "Leather Pants")
suffix2.insert(ItemType.RANGED_LEGS, "Leather Pants")
suffix2.insert(ItemType.MENT_LEGS, "Wool Skirt")
suffix2.insert(ItemType.MELEE_FEET, "Leather Boots")
suffix2.insert(ItemType.RANGED_FEET, "Leather Boots")
suffix2.insert(ItemType.MENT_FEET, "Wool Boots")
suffix2.insert(ItemType.MELEE_HANDS, "Leather Gloves")
suffix2.insert(ItemType.RANGED_HANDS, "Leather Gloves")
suffix2.insert(ItemType.MENT_HANDS, "Wool Sleeves")
suffix2.insert(ItemType.MELEE_ARTIFACT, "Fighting Leather Belt")
suffix2.insert(ItemType.RANGED_ARTIFACT, "Recon Pendant")
suffix2.insert(ItemType.MENT_ARTIFACT, "Sorcerer Spellbook")
suffix2.insert(ItemType.MELEE_WEAPON, "Shortsword")
suffix2.insert(ItemType.RANGED_WEAPON, "Shortbow")
suffix2.insert(ItemType.MENT_WEAPON, "Rod")
suffix2.insert(ItemType.SHIELD, "Iron Buckler")
suffix2.insert(ItemType.FIRE_RING, "Burn Ring")
suffix2.insert(ItemType.ICE_RING, "Frost Ring")
suffix2.insert(ItemType.SHOCK_RING, "Electric Ring")
suffix2.insert(ItemType.DARK_RING, "Shadow Ring")
suffix2.insert(ItemType.XP_RING, "Knowledge Ring")
suffix2.insert(ItemType.GOLD_RING, "Prosperity Ring")
suffix2.insert(ItemType.ITEM_RING, "Loot Ring")

suffix3 = []
suffix3.insert(ItemType.MELEE_HEAD, "Chain Coif")
suffix3.insert(ItemType.RANGED_HEAD, "Chain Coif")
suffix3.insert(ItemType.MENT_HEAD, "Silk Hood")
suffix3.insert(ItemType.MELEE_CHEST, "Chain Cuirass")
suffix3.insert(ItemType.RANGED_CHEST, "Chain Cuirass")
suffix3.insert(ItemType.MENT_CHEST, "Silk Vest")
suffix3.insert(ItemType.MELEE_LEGS, "Chain Greaves")
suffix3.insert(ItemType.RANGED_LEGS, "Chain Greaves")
suffix3.insert(ItemType.MENT_LEGS, "Silk Skirt")
suffix3.insert(ItemType.MELEE_FEET, "Chain Boots")
suffix3.insert(ItemType.RANGED_FEET, "Chain Boots")
suffix3.insert(ItemType.MENT_FEET, "Silk Boots")
suffix3.insert(ItemType.MELEE_HANDS, "Chain Gloves")
suffix3.insert(ItemType.RANGED_HANDS, "Chain Gloves")
suffix3.insert(ItemType.MENT_HANDS, "Silk Sleeves")
suffix3.insert(ItemType.MELEE_ARTIFACT, "Warrior Leather Belt")
suffix3.insert(ItemType.RANGED_ARTIFACT, "Ranger Pendant")
suffix3.insert(ItemType.MENT_ARTIFACT, "Wizard Spellbook")
suffix3.insert(ItemType.MELEE_WEAPON, "Longsword")
suffix3.insert(ItemType.RANGED_WEAPON, "Longbow")
suffix3.insert(ItemType.MENT_WEAPON, "Staff")
suffix3.insert(ItemType.SHIELD, "Crest Shield")
suffix3.insert(ItemType.FIRE_RING, "Blaze Ring")
suffix3.insert(ItemType.ICE_RING, "Freeze Ring")
suffix3.insert(ItemType.SHOCK_RING, "Shock Ring")
suffix3.insert(ItemType.DARK_RING, "Gloom Ring")
suffix3.insert(ItemType.XP_RING, "Intellectual Ring")
suffix3.insert(ItemType.GOLD_RING, "Lucrative Ring")
suffix3.insert(ItemType.ITEM_RING, "Artifact Ring")

suffix4 = []
suffix4.insert(ItemType.MELEE_HEAD, "Plate Helmet")
suffix4.insert(ItemType.RANGED_HEAD, "Plate Helmet")
suffix4.insert(ItemType.MENT_HEAD, "Velvet Hood")
suffix4.insert(ItemType.MELEE_CHEST, "Plate Cuirass")
suffix4.insert(ItemType.RANGED_CHEST, "Plate Cuirass")
suffix4.insert(ItemType.MENT_CHEST, "Velvet Vest")
suffix4.insert(ItemType.MELEE_LEGS, "Plate Greaves")
suffix4.insert(ItemType.RANGED_LEGS, "Plate Greaves")
suffix4.insert(ItemType.MENT_LEGS, "Velvet Skirt")
suffix4.insert(ItemType.MELEE_FEET, "Plate Boots")
suffix4.insert(ItemType.RANGED_FEET, "Plate Boots")
suffix4.insert(ItemType.MENT_FEET, "Velvet Boots")
suffix4.insert(ItemType.MELEE_HANDS, "Plate Gauntlets")
suffix4.insert(ItemType.RANGED_HANDS, "Plate Gauntlets")
suffix4.insert(ItemType.MENT_HANDS, "Velvet Sleeves")
suffix4.insert(ItemType.MELEE_ARTIFACT, "Warlord Leather Belt")
suffix4.insert(ItemType.RANGED_ARTIFACT, "Sniper Pendant")
suffix4.insert(ItemType.MENT_ARTIFACT, "Archwizard Spellbook")
suffix4.insert(ItemType.MELEE_WEAPON, "Greatsword")
suffix4.insert(ItemType.RANGED_WEAPON, "Greatbow")
suffix4.insert(ItemType.MENT_WEAPON, "Greatstaff")
suffix4.insert(ItemType.SHIELD, "Tower Shield")
suffix4.insert(ItemType.FIRE_RING, "Inferno Ring")
suffix4.insert(ItemType.ICE_RING, "Glacial Ring")
suffix4.insert(ItemType.SHOCK_RING, "Volt Ring")
suffix4.insert(ItemType.DARK_RING, "Void Ring")
suffix4.insert(ItemType.XP_RING, "Scholar Ring")
suffix4.insert(ItemType.GOLD_RING, "Affluence Ring")
suffix4.insert(ItemType.ITEM_RING, "Relic Ring")

